mod_name=CMDCam
mod_id=cmdcam
mod_authors=CreativeMD, BluSpring, rPersival
mod_description=Create camera paths.
mod_version=2.2.7-fabric
mod_display_url=https://modrinth.com/mod/cmdcam
release_type=release
github_project=CreativeMD/CMDCam
creativecore_version=2.13.0
curse_id=251244
mod_license=LGPL-3.0-only

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)

forge_version=48.0.39
forge_version_range=[48,)
loader_version_range=[48,)

fabric_loader_version=0.18.1
fabric_api_version=0.116.1+1.21.1
resource_pack_format=34
data_pack_format=34

org.gradle.jvmargs=-Xmx2G
